info:
  name: ${spring.application.name}
  description: onboarding api backend
  version: 1.0.0

scorer:
  adapter: dummy

registry:
  adapter: dummy

strapi:
  base-url: http://localhost:1337/api

spring:
  mvc:
    problemdetails:
      enabled: true

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalArgumentException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - java.lang.IllegalArgumentException
  instances:
    strapi:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalArgumentException
  instances:
    strapi:
      baseConfig: default
