### Valid overlaying request
POST http://localhost:8080/registrations/123/overlay
Content-Type: application/json

{
  "source": "file:///src/test/resources/e2e/overlay_test.yaml"
}

### Valid implementing request
PUT http://localhost:8080/registrations/123/component
Content-Type: application/json

{
  "name": "petstore",
  "revision": "1.0.0"
}

### Valid scoring request
PUT http://localhost:8080/registrations/123/score
Content-Type: application/json


### Valid on-boarding request
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/openapi_valid_candidate.yaml"
}

### Valid request - but missing non-required info
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/openapi_valid_candidate_missing_non_required_info.yaml"
}

### Invalid request - missing required info
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/openapi_invalid_candidate_missing_required_info.yaml"
}

### Valid request - but uri does not exist
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "file:///doesnotexist.yaml"
}

### Valid request - unexpected uri
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "d:/unexpected.yaml"
}

### Invalid request - uri is malformed - bad scheme
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "malformed_uri"
}

### Invalid request - uri is malformed - bad scheme
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "source": "malformed_uri"
}

### Invalid request - operation not allowed
GET http://localhost:8080/registrations
